blank_issues_enabled: true
contact_links:
  - name: Geoman Pro Support via Slack
    url: https://geoman.io/pricing
    about: >
      We offer Geoman Pro users with the "Enterprise and OEM" subscription support via Slack